# Generated by Django 3.2.8 on 2021-10-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField()),
                ('nama_anggota', models.TextField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
                ('no_tlp', models.IntegerField()),
                ('tgl_lahir', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_buku', models.IntegerField()),
                ('judul', models.TextField(max_length=200)),
                ('pengarang', models.TextField(max_length=200)),
                ('tahun_terbit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr_pinjam', models.IntegerField(blank=True)),
                ('nmr_anggota', models.IntegerField()),
                ('buku', models.TextField(max_length=200)),
                ('jml_buku', models.IntegerField()),
                ('tgl_pinjam', models.DateField(auto_now_add=True)),
                ('tgl_kembali', models.DateField()),
            ],
        ),
    ]
