# Generated by Django 3.2.8 on 2021-10-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr_anggota', models.IntegerField()),
                ('nama', models.TextField(max_length=200)),
                ('buku', models.TextField(max_length=200)),
                ('jml_buku', models.IntegerField()),
                ('tgl_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tgl_kembali', models.DateTimeField()),
            ],
        ),
    ]
