# Generated by Django 3.2.8 on 2021-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nmr_anggota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='nmr_anggota',
            field=models.IntegerField(),
        ),
    ]
