# Generated by Django 3.2.8 on 2021-10-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_pinjam_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr_anggota', models.IntegerField()),
                ('nama_anggota', models.TextField(max_length=200)),
                ('jenis_kelamin', models.TextField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
                ('no_tlp', models.IntegerField()),
                ('tgl_lahir', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
