# Generated by Django 3.2.8 on 2021-10-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211028_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='nmr_anggota',
        ),
    ]
