# Generated by Django 3.2.8 on 2021-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211025_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_kembali',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_pinjam',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
